apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
  namespace: datagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      project: datagovernance
      app: configserver
  template:
    metadata:
      labels:
        project: datagovernance
        app: configserver
    spec:
      containers:
      - name: configserver
        image: 10.1.7.121/datagovernance/configserver:V1.7.0
        imagePullPolicy: Always
        env:
        - name: server.address
          value: ${spring.cloud.client.ipAddress}
        - name: eureka.client.service-url.defaultZone
          value: http://10.1.8.159:8041/eureka/
        - name: spring.datasource.driver-class-name
          value: oracle.jdbc.driver.OracleDriver
        - name: spring.datasource.url
          value: jdbc:oracle:thin:@192.168.89.41:1521/synlte
        - name: spring.jpa.properties.hibernate.default_schema
          value: SYNDG_TEST
        - name: spring.datasource.username
          value: syndg_test
        - name: spring.datasource.password
          value: SYNDG_TEST
        - name: spring.jpa.properties.hibernate.dialect
          value: org.hibernate.dialect.Oracle10gDialect
        ports:
        - containerPort: 8088
          name: web
          protocol: TCP
          hostPort: 8088 
        resources:
          limits:
            cpu: 1024m
            memory: 2Gi
          requests:
            cpu: 600m
            memory: 400Mi
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8771
#          initialDelaySeconds: 60
#          timeoutSeconds: 20
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 8771
#          initialDelaySeconds: 60
#          timeoutSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: datagovernance
  labels:
    project: datagovernance
    app: configserver
    svc: configserver-svc
spec:
  selector:
    project: datagovernance
    app: configserver
  ports:
  - name: web
    port: 8088
    targetPort: 8088
  type: NodePort
